### ISSUE TITLE
postgres: Need ability to specify extensions

### ISSUE THREAD

**Issue by moredure** [ariga/atlas-provider-gorm#10]
So atlas migrate diff will not drop them in case specified by handwritten migration file.

**Comment by luantranminh** [comment]
@moredure We have to maintain the integrity of data; hence, the migration file should always be kept tracked. In case you want to do something manually, it may require an additional step to re-compute the hash with the command:

```bash
atlas migrate hash
```

We have documentation on it, and you can explore it [here](https://atlasgo.io/concepts/migration-directory-integrity)
