### ISSUE TITLE
Standalone mode documentation is incomplete

### ISSUE THREAD

**Issue by sonnysideup** [ariga/atlas-provider-gorm#19]
Some details and a proposed solution are outlined in #11 but no official solution was offered, which is why I'm opening this issue.

Adding `import _ "ariga.io/atlas-provider-gorm/gormschema"` to your models package (e.g. `model/model.go`) and then running `go mod tidy` will solve the problem by adding the dependency to your go modules. However, this adds atlas as a direct dependency in your project and thus is no longer really a _standalone_ solution. Am I wrong here?

Is this a bug, an oversight, or am I missing something obvious here?

**Comment by rotemtam** [comment]
Hi,
Thanks for pointing out this gap in the documentation. 
I've updated the docs to include the Go team's recommendation on how to pin versions of tool dependencies. 

The provider relies on the Go compiler and GORM dependencies of your project to work so it is highly recommended to use it this way and not compile it as a _fully_ standalone binary which may or may not work depending on many factors.

Closing this, feel free to re-open if needed.

**Comment by sonnysideup** [comment]
👍🏼 Thank you.
