### ISSUE TITLE
How to `migrate diff` with circular foreign key constraints

### ISSUE THREAD

**Issue by captchanjack** [ariga/atlas-provider-gorm#22]
Hi I'm seeing an error creating migration script using these 2 models that have a circular foreign key constraint on each other:

First table **Event** with a foreign key constraint on **Location**:
```
type Event struct {
	EventID    string    `json:"eventId" gorm:"primaryKey;column:eventId;"`
	LocationID string    `json:"locationId" gorm:"uniqueIndex;column:locationId;"`
	Location   *Location `json:"location" gorm:"foreignKey:locationId;references:locationId;OnUpdate:CASCADE,OnDelete:CASCADE"`

	CreatedAt int `json:"createdAt" gorm:"column:createdAt;"` // Set to current time if it is zero on creating
	UpdatedAt int `json:"updatedAt" gorm:"column:updatedAt;"` // Set to current unix seconds on updating or if it is zero on creating
	DeletedAt int `json:"deletedAt" gorm:"column:deletedAt;"`
}
```

Second table **Location** with a foreign key constraint on **Event**:
```
type Location struct {
	LocationID string `json:"locationId" gorm:"primaryKey;column:locationId;"`
	EventID    string `json:"eventId" gorm:"uniqueIndex;column:eventId;"`
	Event      *Event `json:"event" gorm:"foreignKey:eventId;references:eventId;OnUpdate:CASCADE,OnDelete:CASCADE"`

	CreatedAt int `json:"createdAt" gorm:"column:createdAt;"` // Set to current time if it is zero on creating
	UpdatedAt int `json:"updatedAt" gorm:"column:updatedAt;"` // Set to current unix seconds on updating or if it is zero on creating
	DeletedAt int `json:"deletedAt" gorm:"column:deletedAt;"`
}
```

My loader config looks something like this:
```
func main() {
	stmts, err := gormschema.New("postgres", gormschema.WithConfig(
		&gorm.Config{
			NamingStrategy: schema.NamingStrategy{
				// TablePrefix:   "t_",                         // table name prefix, table for `User` would be `t_User`
				SingularTable: true,                            // use singular table name, table for `User` would be `Users` if false
				NoLowerCase:   true,                            // skip the snake_casing and lowercasing of names
				NameReplacer:  strings.NewReplacer("ID", "Id"), // use name replacer to change struct/field name before convert it to db name
			},
		},
	)).Load(
		&model.Event{},
		&model.Location{},
	)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to load gorm schema: %v\n", err)
		os.Exit(1)
	}
	io.WriteString(os.Stdout, stmts)
}

```

The **error** I'm seeing when i run `atlas migrate diff --env gorm`, basically it tries to create the foreign key on Event.EventId before Event table is created:
```
Error: sql/migrate: read migration directory state: sql/migrate: execute: executing statement "CREATE TABLE \"Location\" (\"locationId\" text,\"eventId\" text,\"createdAt\" bigint,\"updatedAt\" bigint,\"deletedAt\" bigint,PRIMARY KEY (\"locationId\"),CONSTRAINT \"fk_Event_Location\" FOREIGN KEY (\"locationId\") REFERENCES \"Event\"(\"locationId\"));" from version "schema": pq: relation "Event" does not exist
```

Any idea how I can create a diff successfully in this scenario?

**Comment by captchanjack** [comment]
This could be a solution:
[https://stackoverflow.com/questions/76418306/is-it-possible-to-auto-migrate-tables-with-circular-relationships-in-gorm](https://stackoverflow.com/questions/76418306/is-it-possible-to-auto-migrate-tables-with-circular-relationships-in-gorm)

Basically we would need the option to add constraints after the `db.AutoMigrate(...)` with ` db.Migrator().CreateConstraint(...)`.

**Comment by captchanjack** [comment]
Hey I created a PR ([https://github.com/ariga/atlas-provider-gorm/issues/22](https://github.com/ariga/atlas-provider-gorm/issues/22)) to address this for postgres dialect
This issue only happens when FK gorm tags lead to nested FK constraints inside a CREATE TABLE statement, it can be fixed by extracting the FK constraint statements and moving them till after the table creation

**Comment by dorav** [comment]
Hi @captchanjack 
Thanks for reporting on this issue, we are looking into it and will keep you updated

**Comment by dorav** [comment]
Hi @captchanjack 

We have just released this [version](https://github.com/ariga/atlas-provider-gorm/releases/tag/v0.2.0) that supports circular foreign keys by default.

Regarding your example - I think it might be misconfigured as it produces incorrect DDL statements, it seems that the foreign keys are referring to the wrong field. Please try again with this model:

```
type Location struct {
	LocationID string `gorm:"primaryKey;column:locationId;"`
	EventID    string `gorm:"uniqueIndex;column:eventId;size:191"`
	Event      *Event `gorm:"foreignKey:locationId;references:locationId;OnUpdate:CASCADE,OnDelete:CASCADE"`
}

type Event struct {
	EventID    string    `gorm:"primaryKey;column:eventId;"`
	LocationID string    `gorm:"uniqueIndex;column:locationId;size:191"`
	Location   *Location `gorm:"foreignKey:eventId;references:eventId;OnUpdate:CASCADE,OnDelete:CASCADE"`
}
```

**Comment by captchanjack** [comment]
Thanks for getting this in! All good I'm happy to throw away my version
