### ISSUE TITLE
Bug: Standalone option does work

### ISSUE THREAD

**Issue by bozerkins** [ariga/atlas-provider-gorm#27]
This option doesn't really work out of the box: https://github.com/ariga/atlas-provider-gorm?tab=readme-ov-file#standalone

I setup a HCL file, looking something liket his

```hcl
data "external_schema" "gorm" {
  program = [
    "go",
    "run",
    "-mod=mod",
    "ariga.io/atlas-provider-gorm",
    "load",
    "--path", "./models",
    "--dialect", "postgres", // | mysql | sqlite
  ]
}

env "gorm" {
  src = data.external_schema.gorm.url
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}
```

Then i run the diff command
```bash
atlas schema diff --env gorm --to "postgres://root:pass@localhost:5432/database?sslmode=disable"
```

I get an error
```
Error: data.external_schema.gorm: running program /usr/local/go/bin/go: go: finding module for package ariga.io/atlas-provider-gorm
gormschema: .gormschema/atlasloader_gorm_1704573675.go:4:2: missing go.sum entry for module providing package ariga.io/atlas-go-sdk/recordriver; to add:
        go mod download ariga.io/atlas-go-sdk

exit status 1
```

When I run the suggested command and retry the diff command, it says
```
gormschema: go: updates to go.mod needed; to update it:
        go mod tidy

exit status 1
```

After I run mod tidy - it goes back to the previous error.

**Comment by bozerkins** [comment]
Fixed the issues by following this step
https://github.com/ariga/atlas-provider-gorm?tab=readme-ov-file#pinning-go-dependencies

It'd be great to mention that without this it doesn't really work

**Comment by rotemtam** [comment]
Glad you found the solution @bozerkins . Feel free to suggest an improvement to the docs if you don't feel that they are complete or intuitive
