### ISSUE TITLE
[Feature] Supports View

### ISSUE THREAD

**Issue by luantranminh** [ariga/atlas-provider-gorm#38]
### Why

Enriching the functionality for atlas-provider-gorm with better support means attracting more users.
### Design proposal

GORM already supports [View Migration](https://gorm.io/docs/migration.html#Views)

```sql
query := db.Model(&User{}).Where("age > ?", 20)

// Create View
db.Migrator().CreateView("users_pets", gorm.ViewOption{Query: query})
// CREATE VIEW `users_view` AS SELECT * FROM `users` WHERE age > 20
```

I will propose a way to implement this feature in our atlas-gorm-provider.

**Note**: This way won't work with `Standalone` mode. Users have to use `Go code` file mode to be able to migrate views.

https://github.com/ariga/atlas-provider-gorm/blob/e5d6dbfb61aaf99a784b5f8641a8bcace527f1e7/gormschema/gorm.go#L34-L35

We're already having an Option that can configure the Loader. Following this Option Pattern, I'll extend it with a new option WithView. (huge thanks to @giautm)
```go
// gormschema/gorm.go
type Loader struct {
	dialect           string
	config            *gorm.Config
	beforeAutoMigrate []func(*gorm.DB) error
	afterAutoMigrate  []func(*gorm.DB) error
}

type (
	ViewOption struct {
		Query func(*gorm.DB) *gorm.DB
		Replace     bool
	        CheckOption string
	}
)

// WithView creates a view with the given name and options.
func WithView(name string, opt ViewOption) Option {
	return func(l *Loader) {
		l.afterAutoMigrate = append(l.afterAutoMigrate, func(db *gorm.DB) error {
			return db.Migrator().CreateView(name, gorm.ViewOption{
				Query:       opt.Query(db),
				Replace:     opt.Replace,
				CheckOption: opt.CheckOption,
			})
		})
	}
}

```

And the usage will be
```go
// loader/main.go
stmts, err := gormschema.New("mysql",
	gormschema.WithView("ur_adult_now", gormschema.ViewOption{
		Query: func(db *gorm.DB) *gorm.DB {
			return db.Model(&Models.Person{}).Select("id", "name", "age").Where("age > ?", 18)
		},
	}),
).Load(&Models.Address{}, &Models.Person{})
```

**Comment by luantranminh** [comment]
Hey @giautm, I'm about to start working on it. Instead of using the Option Pattern as mentioned above, I will define it as a method for the model, as shown in the following example:

```go
type User struct {
    gorm.Model
    Name string
    Pets []Pet
}

// Views returns view definitions for the model.
func (u User) Views() []gormschema.ViewOption {
    return []gormschema.ViewOption{
        {
            Name: "top_pet_owner",
            Query: func(db *gorm.DB) *gorm.DB {
                return db.Model(&User{}).Select("name, count(pets.id) as pet_count")
            },
        },
    }
}
```

Let me know if there's anything you'd like to discuss about it 🏃‍♂️

**Comment by giautm** [comment]
LGTM, cc @a8m

**Comment by giautm** [comment]
View can be based on a model or not, Luan's suggestion is more flexible

**Comment by luantranminh** [comment]
Oh, I think a8m's "view-based" model makes sense since the view could relate to more than one model/table. If it's tied to the model's method, it might be hard to decide where to put it.

**Comment by luantranminh** [comment]
The model with a `ViewDef` method will be determined as a view.

Example 👇
```go
// gormschema/gorm.go
type (
	View struct {
		Query       func(*gorm.DB) *gorm.DB
		Replace     bool
		CheckOption string
	}
)
```
```go
// models/user.go

// TopPetOwner is a view, which returns owners with the most pets.
// The view will be named as top_pet_owner
type TopPetOwner struct{}

// ViewDef returns the view definition
func (TopPetOwner) ViewDef() gormschema.View {
	return gormschema.View{
		Query: func(db *gorm.DB) *gorm.DB {
			return db.Model(&User{}).Select("name, count(pets.id) as pet_count")
		},
		Replace: true,
	}
}
```

**Comment by a8m** [comment]
> Oh, I think a8m's "view-based" model makes sense since the view could relate to more than one model/table. If it's tied to the model's method, it might be hard to decide where to put it.

Exactly. Views are standalone, but represent a single definition (based on the the dialect). 

> 		Query: func(db *gorm.DB) *gorm.DB {
>			return db.Model(&User{}).Select("name, count(pets.id) as pet_count")
>		},
>		Replace: true,

The `REPLACE` option is not needed.  Also, not sure why `gorm.DB` is needed here (there's no DB at this point). The definition is a simple SQL statement that can be created manually or by some builder.

**Comment by a8m** [comment]
> The `REPLACE` option is used for view creation. It just shows what we can do with a View.

This does not describe the view, but how it is created. Schema definition should not contain it.

> I'm using GORM's query by defining a callback. Why? Because I believe it is more beneficial to leverage GORM's query and let it handle different dialects.

I prefer the view definition to be agnostic to the gorm builder. We can still inject it to this function and allow users to build the query with it or extracts the dialect from it.

**Comment by a8m** [comment]
The builder is needed because the model can be used in different dialects. See the switch above.

The REPLACE used to represent the operation, not the definition. We can omit it here (or let the user decide).

**Comment by luantranminh** [comment]
> model can be used in different dialects. See the switch above

Oh, at first, I didn't understand why we need a dialect here for every view definition, but I get it now. And `atlas_provider_gorm` already does the switch for dialect right here 👇

https://github.com/ariga/atlas-provider-gorm/blob/master/gormschema/gorm.go#L47-L50

So, I guess we can use the GORM builder directly.
