### ISSUE TITLE
Handling enum types

### ISSUE THREAD

**Issue by jeandeducla** [ariga/atlas-provider-gorm#52]
Hello!

I am wondering what is the recommended way to handle custom types and in particular enums?

I am currently doing something very similar what is described [here](https://github.com/go-gorm/gorm/issues/1978#issuecomment-1944113699) but I am not very happy with it since it means you need to maintain the enum definition in more than 1 place.

Is there a better solution? From reading the documentation and testing I understand custom types are not currently handled, if so is this something you plan to tackle in the near future?

Thanks for your help!

**Comment by ronenlu** [comment]
Yes the recommended way to handle custom types is by using [composite schemas](https://atlasgo.io/blog/2024/01/09/atlas-v0-18#composite-schemas).

First you need to define your enum type inside state file, lets call it `schema.sql`:
```sql filename ="schema.sql"
-- Enum type used by gorm.
CREATE TYPE "status" AS ENUM ('active', 'inactive', 'deleted');
```

Next, you need to add the custom type to your GORM model using [type field tag](https://gorm.io/docs/models.html#Fields-Tags):

```diff filename ="models/player.go"
package models

import (
	"gorm.io/gorm"
)

type Player struct {
	gorm.Model
	ID      int `gorm:"primaryKey"`
+	Status  string `gorm:"type:status"`
}

```

Next, you need to use schema composed of your GORM schema and `schema.sql` file, you can do it by using the next `atlas.hcl` config file:

```hcl
data "external_schema" "gorm" {
  program = [
    "go",
    "run",
    "-mod=mod",
    "ariga.io/atlas-provider-gorm",
    "load",
    "--path", "./models",
    "--dialect", "postgres",
  ]
}

data "composite_schema" "app" {
  schema "public" {
    url = "file://schema.sql"
  }
  schema "public" {
    url = data.external_schema.gorm.url
  }
}

env "composed" {
  src = data.composite_schema.app.url
  dev = "docker://postgres/15/dev?search_path=public"
  migration {
    dir = "file://migrations"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}

```

Now, when running: `atlas migrate diff --env composed` new migration file should be created containing the custom enum type:

```sql filename ="20240623142238.sql"
-- Create enum type "status"
CREATE TYPE "status" AS ENUM ('active', 'inactive', 'deleted');
-- Create "players" table
CREATE TABLE "players" (
  "id" bigserial NOT NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  "deleted_at" timestamptz NULL,
  "status" "status" NULL,
  PRIMARY KEY ("id")
);
-- Create index "idx_players_deleted_at" to table: "players"
CREATE INDEX "idx_players_deleted_at" ON "players" ("deleted_at");

```

**Comment by a8m** [comment]
We added an example for this use case. See: https://atlasgo.io/guides/orms/gorm/enum-types
