### ISSUE TITLE
Unable to create indexes with Postgres dialect

### ISSUE THREAD

**Issue by edlundin** [ariga/atlas-provider-gorm#57]
Hi!

I am trying to generate a migration with a unique index, but receive an error `failed to create index with name idx_name`, for the following model:

```go
type Country struct {
	Code   string `json:"code" gorm:"primaryKey;type:char(2);not null"`
	Name   string `json:"name" gorm:"index:idx_name,unique"`
	Iso3   string `json:"iso3" gorm:"type:char(3);not null"`
	Number int    `json:"number" gorm:"not null"`
}
```

Using a debugger, I could tell that things were mostly fine (the SQL statement is correctly generated), however, the issue comes from how the gorm's Migrator checks that the index has been correctly create through the function `HasIndex`. Its current implementation is as followed:

```go
func (m Migrator) HasIndex(value interface{}, name string) bool {
	var count int64
	m.RunWithValue(value, func(stmt *gorm.Statement) error {
		if stmt.Schema != nil {
			if idx := stmt.Schema.LookIndex(name); idx != nil {
				name = idx.Name
			}
		}
		currentSchema, curTable := m.CurrentSchema(stmt, stmt.Table)
		return m.queryRaw(
			"SELECT count(*) FROM pg_indexes WHERE tablename = ? AND indexname = ? AND schemaname = ?", curTable, name, currentSchema,
		).Scan(&count).Error
	})

	return count > 0
}
```

As you can see, the check is done through a SQL query that cannot return the desired result since there is no connected database.

Hence, I propose to fix this the same way the `HasTable` has been done, as its original implementation also uses an SQL query to check for table creation, adding `HasIndex` in the `gormschema.migrator` interface should fix the issue:

```go
func (m *migrator) HasIndex(any,string) bool {
	return true
}
```

I will soon propose a PR for this.

**Comment by edlundin** [comment]
OK, so I forked this repo and added the `HasIndex` function, but that new function is not called. After checking, `HasTable` is not called either.

It means that I do not know yet how to fix this. But the main different between `CreateTable` and `CreateIndex` is that `CreateIndex` always calls `HasIndex` with the SQL query that returns `false` and cause the error instead of continuing the rest of the statement generation.

I'll try to find another solution that does not involve modifying the gorm library.

**Comment by giautm** [comment]
Hello, thank you for reporting this issue. But we can't do anything on our side to fix this yet. Please follow the discussion on the https://github.com/go-gorm/postgres/issues/291 repository.

I'll close this issue, but you can keep in touch with us in our Discord or just comment your question here. Thank you,

**Comment by a8m** [comment]
Follow https://github.com/go-gorm/postgres/pull/292 to get an update when this issue is fixed.

**Comment by luantranminh** [comment]
hi @edlundin, the author of the `gorm/postgres` driver has merged the revert to fix the issue. You can now use `driver/postgres v1.5.11`, which should resolve the problem.

https://github.com/go-gorm/postgres/compare/v1.5.10...v1.5.11
