### ISSUE TITLE
Atlas fails to generate gorm models with index during migrations

### ISSUE THREAD

**Issue by chaitanyapraveen** [ariga/atlas-provider-gorm#58]
I am trying to create migrations for the following gorm model. I was able to create model in the first migration which didn't have index.

When I added index in the subsequent step to trying to generate migrate:diff. Atlas fails with 

Initial Model

> type Job struct {
> 	BaseModel
> 	Type       string          `gorm:"type:varchar(50);not null"`
> 	Status     JobStatus       `gorm:"type:varchar(50);not null;default:'pending';"`
> 	Payload    json.RawMessage `gorm:"type:jsonb;not null"`
> 	StartedAt  *time.Time
> 	FinishedAt *time.Time
> 	Error      *string `gorm:"type:text"`
> 	Attempts   int     `gorm:"default:0"`
> }

Initial Migration

> -- Create "jobs" table
> CREATE TABLE "jobs" (
>   "id" bigserial NOT NULL,
>   "created_at" timestamptz NULL,
>   "updated_at" timestamptz NULL,
>   "type" character varying(50) NOT NULL,
>   "status" character varying(50) NOT NULL DEFAULT 'pending',
>   "payload" jsonb NOT NULL,
>   "started_at" timestamptz NULL,
>   "finished_at" timestamptz NULL,
>   "error" text NULL,
>   "attempts" bigint NULL DEFAULT 0,
>   PRIMARY KEY ("id")
> );

Updated Gorm Model

> type Job struct {
> 	BaseModel
> 	Type       string          `gorm:"type:varchar(50);not null"`
> 	Status     JobStatus       `gorm:"type:varchar(50);not null;default:'pending';index"`
> 	Payload    json.RawMessage `gorm:"type:jsonb;not null"`
> 	StartedAt  *time.Time
> 	FinishedAt *time.Time
> 	Error      *string `gorm:"type:text"`
> 	Attempts   int     `gorm:"default:0"`
> }

> Error: data.external_schema.gorm: running program /usr/local/bin/go: gormschema: failed to load gorm schema: failed to create index with name idx_jobs_status

**Comment by a8m** [comment]
This is a regression bug was introduced by gorm/postgres driver. This patch should revert and fix this: https://github.com/go-gorm/postgres/pull/292


For now, I will suggest you to downgrade the driver package to v1.5.9.
